apiVersion: v1
kind: Template
metadata:
  name: um-configured
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
     run: um-configured
    name: um-configured
  spec:
    replicas: 1
    selector:
      run: um-configured
    template:
      metadata:
        labels:
          run: um-configured
      spec:
        containers:
          - name: um-configured
            image: um_configured:${IMAGE_TAG}
            ports:
            - containerPort: 9000
              protocol: TCP
        serviceAccount: "${SERVICE_ACCOUNT}"
        serviceAccountName: "${SERVICE_ACCOUNT}"
  triggers:
  - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: um-configured
    name: um-configured
  spec:
    ports:
    - name: port-9000
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: um-configured
      deploymentconfig: um-configured
    type: NodePort
  sessionAffinity: None


parameters:
- name: SERVICE_ACCOUNT
  description: "Service Account for higher privileges"

- name: WILDCARD_DOMAIN
  description: "Wildcard domain"
#  required: true

- name: IMAGE_TAG
  description: "Tag of the container image"
  value: latest
  required: true
