apiVersion: v1
kind: Template
metadata:
  name: um
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
     run: um
    name: um
  spec:
    replicas: 1
    selector:
      run: um
    template:
      metadata:
        labels:
          run: um
      spec:
        containers:
          - name: um
            image: um:${IMAGE_TAG}
            ports:
            - containerPort: 9000
              protocol: TCP
        serviceAccount: "${SERVICE_ACCOUNT}"
        serviceAccountName: "${SERVICE_ACCOUNT}"
  triggers:
  - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: um
    name: um
  spec:
    ports:
    - name: port-1
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      run: um

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      run: um
    name: "${ROUTE_NAME}"
  spec:
    port:
      targetPort: 9000
    to:
      kind: Service
      name: um
      weight: 100


parameters:
- name: SERVICE_ACCOUNT
  description: "Service Account for higher privileges"

- name: ROUTE_NAME
  description: "Name of route for port 9000"
  value: "um-9000"

- name: WILDCARD_DOMAIN
  description: "Wildcard domain"
#  required: true

- name: TENANT_NAME
  description: "Tenant Name - this can be the project or namespace name"
  value: webmethods

- name: IMAGE_TAG
  description: "Tag of the container image"
  value: latest
  required: true
